import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MemorEase',
  description: 'Generated by create next app, inspired by quizlet',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1>Nav Bar Placeholder:</h1> <hr></hr><br></br>
        </nav>
       {children}
        </body>
    </html>
  )
}
